POST https://demo.credy.in/api/v1/usermodule/login/
Content-Type: application/json

{
  "username": "testuser",
  "password": "ruDWLeHr9K7ErsUS"
}

###

GET https://demo.credy.in/api/v1/maya/movies/?page=2
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1MzczMSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImV4cCI6MTYyMDQ1MjA5MywiZW1haWwiOiIiLCJvcmlnX2lhdCI6MTYxNzg2MDA5M30.Ihew0WkL101v_1hy7JceYVdNq2KFCpc2UIYhBVkFZXY
